### ISSUE TITLE
原理的jarslink重定向到这里？但是代码怎么完全不一致了？

### ISSUE THREAD

**Issue by cholf** [alipay/sofa-jarslink#105]
原理的jarslink重定向到这里？但是代码怎么完全不一致了？
是下线了么？

**Comment by QilongZhang** [comment]
@cholf  之前的是1.0版本，现在主干的分支代码是基于 SOFAArk 做的。你可以参考文档：
+ http://www.sofastack.tech/sofa-boot/docs/sofa-ark-readme
+ http://www.sofastack.tech/sofa-boot/docs/sofa-jarslink-jarslink-readme

**Comment by cholf** [comment]
> @cholf 之前的是1.0版本，现在主干的分支代码是基于 SOFAArk 做的。你可以参考文档：
> 
> * http://www.sofastack.tech/sofa-boot/docs/sofa-ark-readme
> * http://www.sofastack.tech/sofa-boot/docs/sofa-jarslink-jarslink-readme

你好我使用的是1.0的相关版本，遇到了子jar包配置扫描范围太大的话，会导致主项目service重复扫描，然后导致找不到关联bean；

比如：项目A下面挂着两个jar文件(C,D)，A的包路径是com.sofa.service, C jar包的包路径是com.sofa.insuerance,如果我在C的xml配置<context:component-scan base-package=“com.sofa”/>,这样会导致重新加载A项目的所有注解，如果A项目的XXXService依赖一个dubbo的bean(OrderDetailService)的话，就会报NoSuchBeanDefinitionException: No qualifying bean of type [com.xxx.api.OrderDetailService] found 

我的理解是两个context,所以Cjar是无法获取到已经加载到A项目context的bean的，或者说这个隔离感觉不对，不知道你们那里可以提这个问题，或者你们有遇到么，非常感谢

**Comment by QilongZhang** [comment]
@cholf 非常抱歉，1.0 版本已经不维护了，我之前也没参与1.0 的维护，目前主要发展2.0 版本。
