### ISSUE TITLE
通过jarslink的demo执行结果报错

### ISSUE THREAD

**Issue by grindwheel** [alipay/sofa-jarslink#110]
![image](https://user-images.githubusercontent.com/10232714/50322006-59748400-050e-11e9-947e-555e8e6d829c.png)

**Comment by frinder6** [comment]
这个应该是版本的问题，我将版本升级到 3.0.0 就可以，你可以试试，3.0.0正式版本已经发布了：https://github.com/alipay/sofa-boot

**Comment by grindwheel** [comment]
got it
