### ISSUE TITLE
目前仅支持telnet命令交互方式，有没有支持http 的api交互方式呢

### ISSUE THREAD

**Issue by grindwheel** [alipay/sofa-jarslink#111]
### Your question

目前仅支持telnet命令交互方式，有没有支持http 的api交互方式呢
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Jarslink version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
jarslink 不支持，sofa ark 在 0.6.2-SNAPSHOT 提供了api的支持。
