### ISSUE TITLE
按照demo 打包ark包执行后 Jarslink2.0交互命令 执行不起作用，不报错也不返回任何信息，为什么

### ISSUE THREAD

**Issue by Godhuu** [alipay/sofa-jarslink#113]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Jarslink version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
按照文档校验命令是否正确，如果不行，麻烦请提供相应的 demo.

**Comment by Godhuu** [comment]
重新更新jar包解决了。谢谢。
