### ISSUE TITLE
如何加入钉钉交流群？

### ISSUE THREAD

**Issue by Godhuu** [alipay/sofa-jarslink#114]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- Jarslink version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
钉钉群号：2913639839

![image](https://user-images.githubusercontent.com/8833026/50597558-c27ed300-0ee2-11e9-9490-9998e77e52c1.png)

**Comment by Godhuu** [comment]
群组是否未公开啊，搜索不到。扫码加入显示需要群主邀请加入.

**Comment by QilongZhang** [comment]
可以加入官方微信群：
![image](https://user-images.githubusercontent.com/8833026/50622309-20450680-0f47-11e9-98bf-3dee17de02c0.png)

**Comment by Godhuu** [comment]
好的，谢谢。
