### ISSUE TITLE
请问 jarslink 支持插件的热部署升级吗

### ISSUE THREAD

**Issue by cngddflzw** [alipay/sofa-jarslink#119]
目前据我观察, install 仅仅是 install biz 模块, 假如我的热部署模块中使用了其他 plugin, 现在是不是不支持? 为什么不把 ark 的 DeployPluginStage 的逻辑也一起放到 InstallCommand 里呢?

**Comment by QilongZhang** [comment]
+ 假如我的热部署模块中使用了其他 plugin, 现在是不是不支持? 
> 可以的，直接使用导出类即可，前提是这个 plugin 在启动时就已经包含在 fat jar 中。

+ 为什么不把 ark 的 DeployPluginStage 的逻辑也一起放到 InstallCommand 里呢?
> Plugin 是不允许动态安装卸载的，plugin是所有模块共用的底层依赖。

可以参考 [SOFAArk 文档](https://www.sofastack.tech/sofa-boot/docs/sofa-ark-readme)

**Comment by cngddflzw** [comment]
明白了 谢谢
