### ISSUE TITLE
热部署服务是否可以拥有状态?

### ISSUE THREAD

**Issue by cngddflzw** [alipay/sofa-jarslink#120]
### Your question

热部署服务是否可以拥有状态?

### Your scenes

某些服务的初始化流程可能是依赖业务数据的, 例如 new MyServiceImpl(itemId, itemCount); 这个 itemId 和 itemCount 是从 MyService 调用方获取. 更有甚至的. 可能服务会注册回调, 例如 MyService#addListener(listener)

类似于这样的使用方式, 这些服务可以做到热部署吗? 如何在热部署 activate service 以后恢复这些状态量呢?

**Comment by QilongZhang** [comment]
我理解你说的是服务运行时会生成一部分数据，这些数据会影响后续服务行为。如果这些数据只是局部保存在模块运行时内存，而没有持久化，是不能够热部署的。
