### ISSUE TITLE
Hessian不兼容

### ISSUE THREAD

**Issue by Aliece** [alipay/sofa-jarslink#121]
### Environment

- Jarslink version: 2.0.0-SNAPSHOT
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

 <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-jarslink-ark-starter</artifactId>
            <classifier>ark-plugin</classifier>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>

        
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-plugin</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-starter</artifactId>
            <version>${sofa.boot.version}</version>
        </dependency>

        
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-springboot-starter</artifactId>
            <version>${sofa.ark.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-container</artifactId>
            <version>RELEASE</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-jarslink-runtime</artifactId>
            <version>2.0.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        
        <dependency>
            <groupId>me.qlong.tech</groupId>
            <artifactId>facade</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.caucho</groupId>
            <artifactId>hessian</artifactId>
            <version>4.0.38</version>
        </dependency>

public <T> T fromBytes(byte[] dat, Type type) throws Exception {
        Hessian2Input input = null;
        try {
            input = new Hessian2Input(new ByteArrayInputStream(dat));
            return (T) input.readObject();
        } finally {
            if (input != null) {
                input.close();
            }
        }
    }

    public byte[] toBytes(Object obj) throws Exception{
        Hessian2Output out = null;
        try {
            ByteArrayOutputStream byteArray = new ByteArrayOutputStream();
            out = new Hessian2Output(byteArray);
            out.writeObject(obj);
            out.flush();
            return byteArray.toByteArray();
        } finally {
            if (out != null) {
                try {
                    out.close();
                } catch (IOException e) {
                    logger.warn("close object output stream error! {}", e.getMessage(), e);
                }
            }
        }
    }

使用上述依赖启动后调用hessian的序列化和反序列化的时候会出现加载序列化类的时候由于classloader不一样导致加载类失败，应该是BizClassloader没有设置parent导致的  希望能帮忙解决一下

**Comment by Aliece** [comment]
具体异常信息是这样Caused by: com.caucho.hessian.HessianException: jar:file:xxxxxx/lib/hessian-4.0.38.jar!/META-INF/hessian/serializers: com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer
        at com.caucho.hessian.io.ContextSerializerFactory.initSerializerFiles(ContextSerializerFactory.java:381) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.ContextSerializerFactory.init(ContextSerializerFactory.java:289) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.ContextSerializerFactory.<init>(ContextSerializerFactory.java:124) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:149) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:123) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:116) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.SerializerFactory.createDefault(SerializerFactory.java:140) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.Hessian2Input.findSerializerFactory(Hessian2Input.java:173) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.Hessian2Input.readObjectDefinition(Hessian2Input.java:2183) ~[hessian-4.0.38.jar:?]
        at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2122) ~[hessian-4.0.38.jar:?]

**Comment by QilongZhang** [comment]
@Aliece  麻烦补充下问题复现 Demo.

**Comment by Aliece** [comment]
> @Aliece 麻烦补充下问题复现 Demo.


[app-one.zip](https://github.com/alipay/sofa-jarslink/files/2898909/app-one.zip)

**Comment by QilongZhang** [comment]
@Aliece  上传的 demo  解压有问题哈，能否直接给个git 地址

**Comment by Aliece** [comment]
> @Aliece 上传的 demo 解压有问题哈，能否直接给个git 地址

https://github.com/Aliece/SofaTest

**Comment by QilongZhang** [comment]
@Aliece  个人认为这是 Hessian 4.0.2 兼容性问题，只有在 IDE 启动时会报错，java -jar 启动不会报错。另外如果将 hessian 降低到 3.x 版本，也没有报错。

**Comment by Aliece** [comment]
@QilongZhang 请问您使用java -jar启动是启动了xxx-executable-ark.jar么

**Comment by QilongZhang** [comment]
> @QilongZhang 请问您使用java -jar启动是启动了xxx-executable-ark.jar么

是的

**Comment by QilongZhang** [comment]
关注 https://github.com/alipay/sofa-hessian/issues/38 ， 计划在 sofa-hessian 4.0.3 兼容这个问题。
