### ISSUE TITLE
Jarslink2.0 支持客户端 API 管理多应用生命周期

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-jarslink#91]
Jarslink2.0 目前支持通过 telnet 连接输入指令，做到管理多应用生命周期，如装载、卸载。需要提供更加灵活的 API 形式管理多应用生命周期。

**Comment by yunyl** [comment]
这个功能什么时候能发布呢？

**Comment by QilongZhang** [comment]
https://github.com/alipay/sofa-ark/pull/137  在sofa-ark 中实现了这个功能。
