### ISSUE TITLE
Jarslink2.0 支持多个 Spring Boot Web 应用合并部署

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-jarslink#92]
目前多应用合并部署时，Jarslink2.0 只支持最多一个 Spring Boot Web 应用，需要支持多个 Web 应用合并部署。

**Comment by jackcailj** [comment]
请问2.1版本大概什么时候发布？

**Comment by jackcailj** [comment]
目前需要多个web应用合并部署的功能

**Comment by QilongZhang** [comment]
开发中了~~  我们会尽快发布

**Comment by yunyl** [comment]
快发布了吗？

**Comment by QilongZhang** [comment]
@yunyl  嗯，紧张开发中，会在 https://github.com/alipay/sofa-ark/milestone/8 SOFAArk v0.6.0支持

**Comment by SingleByte** [comment]
同求。。。期待~

**Comment by QilongZhang** [comment]
https://github.com/alipay/sofa-ark/pull/203

已在 sofaark 0.6.0 支持，参考 https://github.com/alipay/sofa-ark/issues/202

@yunyl  @jackcailj  @SingleByte
