### ISSUE TITLE
按照文档“启动 SOFABoot 应用”出现“Failed to execute goal com.mycila:license-maven-plugin:3.0:remove” 错误

### ISSUE THREAD

**Issue by larrychao** [alipay/sofa-jarslink#93]
### 按照官方文档介绍的sofaboot-sample-with-isle 运行 SOFABoot出现Failed to execute goal com.mycila:license-maven-plugin:3.0:remove 始终过不去

错误内容：
Failed to execute goal com.mycila:license-maven-plugin:3.0:remove (default) on project sofa-boot-run: Execution default of goal com.mycila:license-maven-plugin:3.0:remove failed: Cannot read header document /Users/XXX/CODE/ThirdParty/sofa-boot/sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/../../HEADER. Cause: Resource /Users/XXX/CODE/ThirdParty/sofa-boot/sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/../../HEADER not found in file system, classpath or URL: no protocol: /Users/XXX/CODE/ThirdParty/sofa-boot/sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/../../HEADER -> [Help 1]
[ERROR] 

错误信息中的XXX是我的用户名

### pom文件的plugin如下
`<plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${license.maven.plugin}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>remove</goal>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <quiet>true</quiet>
                    <header>${main.user.dir}/HEADER</header> 这里的HEADER找不到，不知道这个HEADER是什么用意
                    <includes>
                        <include>**/src/main/java/**</include>
                        <include>**/src/test/java/**</include>
                    </includes>
                    <strictCheck>true</strictCheck>
                    <mapping>
                        <java>SLASHSTAR_STYLE</java>
                    </mapping>
                </configuration>
            </plugin>`

我尝试清理本地仓库中 com.mycila 依然无效

### Environment

- Jarslink version: 3.5.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):mac
- Maven version:3.5.4
- IDE version:intellij 2018.1 community

**Comment by QilongZhang** [comment]
@larrychao   是哪个工程？ 另外是在哪个目录中执行该命令的呢

**Comment by larrychao** [comment]
@QilongZhang 我用得失SOFABoot 2.4.0的代码
运行的工程是sofa-boot-run 2.4.0， 2.5.0的存在相同的问题
是不是不能单独运行？
因为我直接sofa-boot-run的父项目sofaboot-sample-with-isle就是正确的

**Comment by QilongZhang** [comment]
@larrychao  sofa-boot-run 是 sofaboot-sample-with-isle 工程的子模块，在代码工程配置了 license-maven-plugin 插件，会用到 SOFABoot 工程个目录中的 HEADER 文件。推荐直接在 sofaboot-sample-with-isle 使用 mvn clean install ，如果在单独的子模块执行 mvn 命令，因为相对路径的问题，会导致 license 插件找不到 HEADER 文件。
