### ISSUE TITLE
打包插件能否提供gradle支持

### ISSUE THREAD

**Issue by Linjj** [alipay/sofa-jarslink#95]
项目是使用gradle构建的，能不能提供gradle打包支持

**Comment by QilongZhang** [comment]
关注这个 https://github.com/alipay/sofa-ark/issues/73

内部提供 gradle 的构建插件优先级不会太高，希望PR.

**Comment by Linjj** [comment]
还有一个问题，什么时候支持application.yml的配置方式？

**Comment by QilongZhang** [comment]
@Linjj 一直是支持的，是有什么问题吗？

**Comment by Linjj** [comment]
spring.application.name在application.yml配置了，但是项目启动的时候会报找不到该属性，换成application.properties的配置格式，就能正常运行，具体的异常信息现在没办法提供

**Comment by QilongZhang** [comment]
@Linjj  能否提供一个复现的demo, 因为我知道一直是有人使用 application.yml 的

**Comment by Linjj** [comment]
不好意思，应该是昨天哪里配错了，我今天拿spring-boot-transform-sample 示例项目改造没发现有这个问题，请忽略
